export const ApplicantsSnapshot: Applicant[] = [
  {
    "id": "YvUY9S2ITt531AjM1cUCkWiq",
    "name": "Maja Eklund",
    "email": "tbergstrom.volley@mail.com",
    "time": "1/16/2025 13:04:34",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Sometimes hesitant when blocking, but good timing overall.",
        "id": "lbi3tviXfR",
        "date": "2025-02-04T19:36:03.495Z",
        "author_tryouts_string": "Erik Larsson"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Very powerful spikes, needs to work on consistency.",
        "id": "hum20umLVh",
        "date": "2025-02-04T19:41:15.136Z",
        "author_tryouts_string": "Anna Sj\u00f6berg"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Great instincts and reads the game well.",
        "id": "Ecq23vyn6K",
        "date": "2025-02-04T19:52:37.588Z",
        "author_tryouts_string": "Anna Sj\u00f6berg"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Needs to work on serve-receive but aggressive on the net.",
        "id": "AHbl0tpo6W",
        "date": "2025-02-04T20:53:32.924Z",
        "author_tryouts_string": "Johan Nilsson"
      },
      {
        "author": "FSg8syNtAKzY",
        "content": "Worked well in drills, could use more vocal presence.",
        "id": "qZ7CMPntBW",
        "date": "2025-02-05T14:54:45.320Z",
        "author_tryouts_string": "Anna Sj\u00f6berg"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Fantastic energy and motivation, lifts the team.",
        "id": "SviQ8LMV6g",
        "date": "2025-02-04T16:09:33.789Z",
        "author_tryouts_string": "Johan Nilsson"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Inconsistent but showed promise during warm-ups.",
        "id": "6GmnAOTKix",
        "date": "2025-02-04T21:54:49.903Z",
        "author_tryouts_string": "Fredrik Berg"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Fantastic energy and motivation, lifts the team.",
        "id": "oK5xMqCWRO",
        "date": "2025-02-06T09:24:16.707Z",
        "author_tryouts_string": "David Karlsson"
      }
    ],
    "nationality": "French",
    "studyAtKTH": "",
    "studyDuration": "Not studying at KTH or other university",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Prefer not",
      "opposite": "Ok",
      "middle": "Ok",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Interested in both korpen and league games.",
    "depositInfo": "",
    "teamExpectations": "Fully competitive",
    "availability": "",
    "source": "A friend told me about it",
    "previousExperience": "Played in a Club 2-4 years +",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 6
  },
  {
    "id": "RBzXoaKYEgoZ2CM8AMW1YLyx",
    "name": "Lucas Sandberg",
    "email": "liam.gustafsson@kth.se",
    "time": "1/16/2025 18:35:52",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Fantastic energy and motivation, lifts the team.",
        "id": "8epomJz9Mh",
        "date": "2025-02-04T20:38:47.204Z",
        "author_tryouts_string": "Emma Nystr\u00f6m"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Good communication on court, seems like a team player.",
        "id": "mpZvCh72EW",
        "date": "2025-02-04T21:50:45.748Z",
        "author_tryouts_string": "Erik Larsson"
      },
      {
        "author": "Cm6Mf0trFCpC",
        "content": "Has solid fundamentals and a strong serve.",
        "id": "yVTiVRvmnd",
        "date": "2025-02-04T22:15:33.759Z",
        "author_tryouts_string": "Fredrik Berg"
      },
      {
        "author": "FSg8syNtAKzY",
        "content": "Sometimes hesitant when blocking, but good timing overall.",
        "id": "rEgiVFQlY9",
        "date": "2025-02-05T15:07:33.614Z",
        "author_tryouts_string": "Fredrik Berg"
      }
    ],
    "nationality": "Dutch",
    "studyAtKTH": "",
    "studyDuration": "Not studying at KTH or other university",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Prefer not",
      "opposite": "Preferred",
      "middle": "Ok",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Open to any position, just wants to be on court.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "Instagram Page",
    "previousExperience": "Played in a Club 1-2 years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 73
  },
  {
    "id": "zvVXGLq49i2n83bYJV7t1FCS",
    "name": "Emil Norberg",
    "email": "lucas.sandberg@gmail.com",
    "time": "1/16/2025 18:44:09",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Very friendly, gave good energy to the team.",
        "id": "bDBMDMwkxO",
        "date": "2025-02-04T20:05:01.345Z",
        "author_tryouts_string": "Sara Lund"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Struggled a bit with positioning but has good potential.",
        "id": "Im84JPf1n5",
        "date": "2025-02-04T21:47:54.903Z",
        "author_tryouts_string": "Erik Larsson"
      },
      {
        "author": "Cm6Mf0trFCpC",
        "content": "Fantastic energy and motivation, lifts the team.",
        "id": "VYhitICLGW",
        "date": "2025-02-04T22:12:55.808Z",
        "author_tryouts_string": "Mikaela Andersson"
      },
      {
        "author": "FSg8syNtAKzY",
        "content": "Worked well in drills, could use more vocal presence.",
        "id": "IsLVszKwtY",
        "date": "2025-02-05T15:02:43.520Z",
        "author_tryouts_string": "Johan Nilsson"
      }
    ],
    "nationality": "Dutch",
    "studyAtKTH": "",
    "studyDuration": "2+ years",
    "THSMember": "Yes",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Prefer not",
      "opposite": "Prefer not",
      "middle": "Ok",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Looking to improve and meet new people.",
    "depositInfo": "",
    "teamExpectations": "Fully competitive",
    "availability": "",
    "source": "A friend told me about it",
    "previousExperience": "Casual Play only",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 73
  },
  {
    "id": "kcw9uubPnq9h2oaU1vsyTCrH",
    "name": "Lucas Sandberg",
    "email": "emil.norberg@stud.kth.se",
    "time": "1/16/2025 18:49:05",
    "comments": [
      {
        "author": "Cm6Mf0trFCpC",
        "content": "Very powerful spikes, needs to work on consistency.",
        "id": "qCjKz5Usls",
        "date": "2025-02-06T21:19:40.073Z",
        "author_tryouts_string": "David Karlsson"
      }
    ],
    "nationality": "French",
    "studyAtKTH": "",
    "studyDuration": "Not studying at KTH or other university",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Ok",
      "setter": "Ok",
      "opposite": "Ok",
      "middle": "Ok",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Available most evenings and weekends.",
    "depositInfo": "",
    "teamExpectations": "Fully competitive",
    "availability": "",
    "source": "A friend told me about it",
    "previousExperience": "Played in a Club 1-2 years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Women's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 47
  },
  {
    "id": "rz2G9LkxXhAloSfsg4HkKelM",
    "name": "Alex Johansson",
    "email": "jamie_a@kth.se",
    "time": "1/16/2025 19:03:43",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Needs to work on serve-receive but aggressive on the net.",
        "id": "OoV00h7iwF",
        "date": "2025-02-04T20:35:17.521Z",
        "author_tryouts_string": "Sara Lund"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Great instincts and reads the game well.",
        "id": "Bf2dnBc68s",
        "date": "2025-02-04T21:45:58.803Z",
        "author_tryouts_string": "Anna Sj\u00f6berg"
      },
      {
        "author": "FSg8syNtAKzY",
        "content": "Struggled a bit with positioning but has good potential.",
        "id": "Mpw8lWg3XF",
        "date": "2025-02-05T14:59:38.270Z",
        "author_tryouts_string": "Fredrik Berg"
      }
    ],
    "nationality": "Estonian",
    "studyAtKTH": "",
    "studyDuration": "Not studying at KTH or other university",
    "THSMember": "I intend to become one soon",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Prefer not",
      "opposite": "Preferred",
      "middle": "Ok",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Moving to Stockholm recently, looking for community.",
    "depositInfo": "",
    "teamExpectations": "Fully competitive",
    "availability": "",
    "source": "Youtube",
    "previousExperience": "Casual Play only",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 87
  },
  {
    "id": "RHVOzRnYuDEKmUVUpUkQbarx",
    "name": "Maja Eklund",
    "email": "emil.norberg@stud.kth.se",
    "time": "1/16/2025 19:05:54",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Fantastic energy and motivation, lifts the team.",
        "id": "Z8NJXhCINX",
        "date": "2025-02-04T19:41:56.896Z",
        "author_tryouts_string": "Erik Larsson"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Great instincts and reads the game well.",
        "id": "uN4puAsw5B",
        "date": "2025-02-04T21:49:22.843Z",
        "author_tryouts_string": "David Karlsson"
      },
      {
        "author": "FSg8syNtAKzY",
        "content": "Fantastic energy and motivation, lifts the team.",
        "id": "MT12GVPUoL",
        "date": "2025-02-05T15:06:27.213Z",
        "author_tryouts_string": "Fredrik Berg"
      }
    ],
    "nationality": "Polish",
    "studyAtKTH": "",
    "studyDuration": "2+ years",
    "THSMember": "Yes",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Prefer not",
      "opposite": "Prefer not",
      "middle": "Preferred",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Interested in both korpen and league games.",
    "depositInfo": "",
    "teamExpectations": "Fully competitive",
    "availability": "",
    "source": "Instagram Page",
    "previousExperience": "Played in a Club 1-2 years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 86
  },
  {
    "id": "UXnVf2ZoiZPRt2FncGjilPTZ",
    "name": "Liam Gustafsson",
    "email": "ella.bjork93@gmail.com",
    "time": "1/16/2025 19:06:44",
    "comments": [],
    "nationality": "German",
    "studyAtKTH": "",
    "studyDuration": "",
    "THSMember": "",
    "preferredRoles": {
      "libero": "",
      "setter": "",
      "opposite": "",
      "middle": "",
      "wingSpiker": ""
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Looking for serious play with good vibes.",
    "depositInfo": "",
    "teamExpectations": "",
    "availability": "",
    "source": "",
    "previousExperience": "",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "",
    "paid_deposit": "Not paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 11
  },
  {
    "id": "QsRvf3BTPUctiyiFBqFSOkfq",
    "name": "Maja Eklund",
    "email": "emil.norberg@stud.kth.se",
    "time": "1/16/2025 19:22:14",
    "comments": [],
    "nationality": "Icelandic",
    "studyAtKTH": "",
    "studyDuration": "1.5 years",
    "THSMember": "Yes",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Ok",
      "opposite": "Ok",
      "middle": "Ok",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Very dedicated to the sport.",
    "depositInfo": "",
    "teamExpectations": "I would like to play competetive but also have fun! ",
    "availability": "",
    "source": "A friend told me about it",
    "previousExperience": "Casual Play only",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Women's team",
    "paid_deposit": "Not paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 15
  },
  {
    "id": "VK4DuO9gkZRarcGaBNtSvmxQ",
    "name": "Lucas Sandberg",
    "email": "william.oberg91@yahoo.com",
    "time": "1/16/2025 20:25:05",
    "comments": [
      {
        "author": "FSg8syNtAKzY",
        "content": "Lacked court awareness but adapted quickly by the end.",
        "id": "nrQ3H05LOv",
        "date": "2025-02-05T15:14:38.592Z",
        "author_tryouts_string": "Mikaela Andersson"
      }
    ],
    "nationality": "Swedish",
    "studyAtKTH": "",
    "studyDuration": "Not studying at KTH or other university",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Preferred",
      "opposite": "Prefer not",
      "middle": "Prefer not",
      "wingSpiker": "Prefer not"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Loves the sport and wants to play more competitively.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "Instagram Page",
    "previousExperience": "Played in a Club 4+ years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Not paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 1
  },
  {
    "id": "LSWT1W6dO0BW570pyw7zV2Is",
    "name": "Sofia Nyberg",
    "email": "caseyekstrom23@outlook.com",
    "time": "1/16/2025 20:36:21",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Inconsistent but showed promise during warm-ups.",
        "id": "kKZlIopBRG",
        "date": "2025-02-04T19:21:56.643Z",
        "author_tryouts_string": "Emma Nystr\u00f6m"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Great instincts and reads the game well.",
        "id": "da5oPEmA9I",
        "date": "2025-02-04T20:37:23.802Z",
        "author_tryouts_string": "Mikaela Andersson"
      },
      {
        "author": "FSg8syNtAKzY",
        "content": "Spikes were hard to receive, great offensive presence.",
        "id": "wNG4kvtFfM",
        "date": "2025-02-05T15:12:24.573Z",
        "author_tryouts_string": "Erik Larsson"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Has solid fundamentals and a strong serve.",
        "id": "eRkXLP8Ij9",
        "date": "2025-02-06T09:13:46.469Z",
        "author_tryouts_string": "Emma Nystr\u00f6m"
      }
    ],
    "nationality": "Polish",
    "studyAtKTH": "",
    "studyDuration": "1.5 years",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Prefer not",
      "opposite": "Prefer not",
      "middle": "Preferred",
      "wingSpiker": "Prefer not"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Interested in both korpen and league games.",
    "depositInfo": "",
    "teamExpectations": "Fully competitive",
    "availability": "",
    "source": "A friend told me about it",
    "previousExperience": "Played in a Club 4+ years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 77
  },
  {
    "id": "DPXXmkBZcXvJ7y8X5BHRRqpy",
    "name": "Sofia Nyberg",
    "email": "morgan.svensson@hotmail.com",
    "time": "1/16/2025 21:34:45",
    "comments": [
      {
        "author": "ZgdggtnW7ePQ",
        "content": "Spikes were hard to receive, great offensive presence.",
        "id": "3Wlr4dsY6k",
        "date": "2025-02-06T19:52:05.870Z",
        "author_tryouts_string": "Anna Sj\u00f6berg"
      },
      {
        "author": "Cm6Mf0trFCpC",
        "content": "Really solid middle blocker, reads the setter well.",
        "id": "fhHCt2H9aS",
        "date": "2025-02-06T21:18:14.536Z",
        "author_tryouts_string": "David Karlsson"
      }
    ],
    "nationality": "Estonian",
    "studyAtKTH": "",
    "studyDuration": "6 months",
    "THSMember": "Yes",
    "preferredRoles": {
      "libero": "Ok",
      "setter": "Prefer not",
      "opposite": "Ok",
      "middle": "Prefer not",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Hoping to find a team that trains regularly.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "THS International Reception",
    "previousExperience": "Played in a Club 4+ years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Women's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 88
  },
  {
    "id": "8nNbeCEpyDf1Qs7cNwYQGr09",
    "name": "Casey Ekstr\u00f6m",
    "email": "lucas.sandberg@gmail.com",
    "time": "1/16/2025 23:45:28",
    "comments": [
      {
        "author": "Cm6Mf0trFCpC",
        "content": "Played well under pressure and made very few errors.",
        "id": "QlQDGRL5ke",
        "date": "2025-02-06T21:25:39.618Z",
        "author_tryouts_string": "Erik Larsson"
      }
    ],
    "nationality": "Estonian",
    "studyAtKTH": "",
    "studyDuration": "6 months",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Preferred",
      "setter": "Prefer not",
      "opposite": "Ok",
      "middle": "Prefer not",
      "wingSpiker": "Prefer not"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Excited to get back into volleyball after a year off.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "Instagram Page",
    "previousExperience": "Played in a Club 2-4 years +",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Women's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 20
  },
  {
    "id": "OMmzN91VUigEega8pPygUjWp",
    "name": "Nora Hellstr\u00f6m",
    "email": "lucas.sandberg@gmail.com",
    "time": "1/17/2025 7:44:39",
    "comments": [],
    "nationality": "Norwegian",
    "studyAtKTH": "",
    "studyDuration": "",
    "THSMember": "",
    "preferredRoles": {
      "libero": "",
      "setter": "",
      "opposite": "",
      "middle": "",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Available most evenings and weekends.",
    "depositInfo": "",
    "teamExpectations": "",
    "availability": "",
    "source": "",
    "previousExperience": "",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "",
    "paid_deposit": "Not paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 77
  },
  {
    "id": "Wt7A01bJzDNYTMdeRiKdQdG5",
    "name": "Nora Hellstr\u00f6m",
    "email": "ella.bjork93@gmail.com",
    "time": "1/17/2025 12:28:31",
    "comments": [
      {
        "author": "l2ioN36H1a0g",
        "content": "Needs to work on serve-receive but aggressive on the net.",
        "id": "aoLzlkAZ7T",
        "date": "2025-02-06T09:02:39.445Z",
        "author_tryouts_string": "Anna Sj\u00f6berg"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Has solid fundamentals and a strong serve.",
        "id": "95dN3W8CHC",
        "date": "2025-02-06T09:18:10.682Z",
        "author_tryouts_string": "Sara Lund"
      }
    ],
    "nationality": "British",
    "studyAtKTH": "",
    "studyDuration": "6 months",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Prefer not",
      "opposite": "Ok",
      "middle": "Preferred",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Hoping to find a team that trains regularly.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "Instagram Page",
    "previousExperience": "Casual Play only",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 52
  },
  {
    "id": "C17DnDrWmQGGA5kzDjyRZelj",
    "name": "Alex Johansson",
    "email": "lucas.sandberg@gmail.com",
    "time": "1/17/2025 12:28:31",
    "comments": [],
    "nationality": "German",
    "studyAtKTH": "",
    "studyDuration": "6 months",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Prefer not",
      "opposite": "Ok",
      "middle": "Preferred",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Excited to get back into volleyball after a year off.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "Instagram Page",
    "previousExperience": "Casual Play only",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Not paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 2
  },
  {
    "id": "1KtpcWCYmO2WjYbvkGcmRG27",
    "name": "Emil Norberg",
    "email": "ella.bjork93@gmail.com",
    "time": "1/17/2025 19:33:19",
    "comments": [],
    "nationality": "British",
    "studyAtKTH": "",
    "studyDuration": "Not studying at KTH or other university",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Preferred",
      "setter": "Preferred",
      "opposite": "Ok",
      "middle": "Prefer not",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Willing to train hard and commit to the team's goals.",
    "depositInfo": "",
    "teamExpectations": "Fully competitive",
    "availability": "",
    "source": "A friend told me about it",
    "previousExperience": "Played in a Club 2-4 years +",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Not paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 45
  },
  {
    "id": "r1hOaV5IybkP217ltA8LT1iS",
    "name": "Taylor Bergstr\u00f6m",
    "email": "j.lindqvist21@yahoo.com",
    "time": "1/18/2025 21:19:28",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Sometimes hesitant when blocking, but good timing overall.",
        "id": "EWDoeWC2KG",
        "date": "2025-02-04T19:36:35.247Z",
        "author_tryouts_string": "David Karlsson"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Inconsistent but showed promise during warm-ups.",
        "id": "thzHEiPKyt",
        "date": "2025-02-04T19:50:25.307Z",
        "author_tryouts_string": "Sara Lund"
      },
      {
        "author": "FSg8syNtAKzY",
        "content": "Lacked court awareness but adapted quickly by the end.",
        "id": "ZOqNuMQZa9",
        "date": "2025-02-05T11:56:46.495Z",
        "author_tryouts_string": "Erik Larsson"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Great instincts and reads the game well.",
        "id": "QgXIZ3RMjr",
        "date": "2025-02-06T09:03:56.089Z",
        "author_tryouts_string": "Anna Sj\u00f6berg"
      }
    ],
    "nationality": "Icelandic",
    "studyAtKTH": "",
    "studyDuration": "Not studying at KTH or other university",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Ok",
      "setter": "Ok",
      "opposite": "Ok",
      "middle": "Ok",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Interested in both korpen and league games.",
    "depositInfo": "",
    "teamExpectations": "I'm quite competitive volleyball player and I'm hungry for improvement but I also social and I like the fun side of volleyboll as well.",
    "availability": "",
    "source": "A friend and ex teammate that told me about KTH volleyball team",
    "previousExperience": "Played in a Club 2-4 years +",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 30
  },
  {
    "id": "epWxxTJQGntqXbfT97wBq2uG",
    "name": "Ella Bj\u00f6rk",
    "email": "oscar.dahl@outlook.com",
    "time": "1/19/2025 1:48:57",
    "comments": [],
    "nationality": "Dutch",
    "studyAtKTH": "",
    "studyDuration": "6 months",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Ok",
      "opposite": "Preferred",
      "middle": "Ok",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Looking to improve and meet new people.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "Instagram Page",
    "previousExperience": "Played in a Club 1-2 years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 35
  },
  {
    "id": "g9m2Skvxhd2UjWbVCLdXSDEP",
    "name": "William \u00d6berg",
    "email": "j.lindqvist21@yahoo.com",
    "time": "1/19/2025 20:53:02",
    "comments": [
      {
        "author": "l2ioN36H1a0g",
        "content": "Played well under pressure and made very few errors.",
        "id": "3UtQNtejvq",
        "date": "2025-02-06T09:35:17.990Z",
        "author_tryouts_string": "David Karlsson"
      }
    ],
    "nationality": "German",
    "studyAtKTH": "",
    "studyDuration": "Not studying at KTH or other university",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Ok",
      "setter": "Ok",
      "opposite": "Preferred",
      "middle": "Prefer not",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Previously coached youth teams, now wants to play.",
    "depositInfo": "",
    "teamExpectations": "Fully competitive",
    "availability": "",
    "source": "A friend told me about it",
    "previousExperience": "Played in a Club 4+ years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 12
  },
  {
    "id": "iASBc0YJerG83WdeoQQwhqDI",
    "name": "Sofia Nyberg",
    "email": "caseyekstrom23@outlook.com",
    "time": "1/20/2025 9:46:51",
    "comments": [
      {
        "author": "Cm6Mf0trFCpC",
        "content": "Inconsistent but showed promise during warm-ups.",
        "id": "bhhe9c1sQA",
        "date": "2025-02-06T21:23:30.445Z",
        "author_tryouts_string": "Anna Sj\u00f6berg"
      }
    ],
    "nationality": "Norwegian",
    "studyAtKTH": "",
    "studyDuration": "6 months",
    "THSMember": "Yes",
    "preferredRoles": {
      "libero": "Ok",
      "setter": "Ok",
      "opposite": "Ok",
      "middle": "Ok",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Loves the sport and wants to play more competitively.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "THS website",
    "previousExperience": "High School",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Women's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 81
  },
  {
    "id": "ajc9WEbHSwLwMu4a21Gb7c4f",
    "name": "Oscar Dahl",
    "email": "morgan.svensson@hotmail.com",
    "time": "1/20/2025 17:17:55",
    "comments": [
      {
        "author": "ZgdggtnW7ePQ",
        "content": "Fantastic energy and motivation, lifts the team.",
        "id": "6wa8pNvP5h",
        "date": "2025-02-06T19:50:29.921Z",
        "author_tryouts_string": "Erik Larsson"
      },
      {
        "author": "Cm6Mf0trFCpC",
        "content": "Really solid middle blocker, reads the setter well.",
        "id": "smfVCsGFLr",
        "date": "2025-02-06T21:22:28.562Z",
        "author_tryouts_string": "Erik Larsson"
      }
    ],
    "nationality": "Polish",
    "studyAtKTH": "",
    "studyDuration": "Not studying at KTH or other university",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Ok",
      "setter": "Preferred",
      "opposite": "Ok",
      "middle": "Prefer not",
      "wingSpiker": "Prefer not"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Willing to train hard and commit to the team's goals.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "A friend told me about it",
    "previousExperience": "Played in a Club 4+ years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Women's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 66
  },
  {
    "id": "g0qWtnKFhwjFyFHK6wAmSuUz",
    "name": "Emil Norberg",
    "email": "alex.johansson95@gmail.com",
    "time": "1/20/2025 18:03:53",
    "comments": [],
    "nationality": "Norwegian",
    "studyAtKTH": "",
    "studyDuration": "",
    "THSMember": "",
    "preferredRoles": {
      "libero": "",
      "setter": "",
      "opposite": "",
      "middle": "",
      "wingSpiker": ""
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Very dedicated to the sport.",
    "depositInfo": "",
    "teamExpectations": "",
    "availability": "",
    "source": "",
    "previousExperience": "",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "",
    "paid_deposit": "Not paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 98
  },
  {
    "id": "OSrC3OZQdky1AS4p4PfZhWCk",
    "name": "Alex Johansson",
    "email": "tbergstrom.volley@mail.com",
    "time": "1/20/2025 18:37:21",
    "comments": [],
    "nationality": "Estonian",
    "studyAtKTH": "",
    "studyDuration": "6 months",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Preferred",
      "setter": "Prefer not",
      "opposite": "Ok",
      "middle": "Prefer not",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Loves the sport and wants to play more competitively.",
    "depositInfo": "",
    "teamExpectations": "I\u00e2\u20ac\u2122m looking for Social Play but if I have the chance to join the team, It will be a great experience ",
    "availability": "",
    "source": "Instagram Page",
    "previousExperience": "Played in a Club 4+ years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Not paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 20
  },
  {
    "id": "5PnitrIKXvGCXx4iSwHsYf58",
    "name": "Emil Norberg",
    "email": "morgan.svensson@hotmail.com",
    "time": "1/20/2025 18:38:33",
    "comments": [],
    "nationality": "Polish",
    "studyAtKTH": "",
    "studyDuration": "6 months",
    "THSMember": "I intend to become one soon",
    "preferredRoles": {
      "libero": "Ok",
      "setter": "Prefer not",
      "opposite": "Preferred",
      "middle": "Preferred",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Played a lot before and now returning after a break.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "Instagram Page",
    "previousExperience": "Played in a Club 1-2 years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Women's team",
    "paid_deposit": "Not paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 49
  },
  {
    "id": "ZLlUNOxMzs3O88PC2nAZwWUz",
    "name": "Emil Norberg",
    "email": "lucas.sandberg@gmail.com",
    "time": "1/20/2025 18:51:51",
    "comments": [
      {
        "author": "ZgdggtnW7ePQ",
        "content": "Has solid fundamentals and a strong serve.",
        "id": "GI7sxpDcEW",
        "date": "2025-02-06T19:48:31.688Z",
        "author_tryouts_string": "Anna Sj\u00f6berg"
      },
      {
        "author": "Cm6Mf0trFCpC",
        "content": "High potential, just needs more match experience.",
        "id": "zFjZO8Rqj1",
        "date": "2025-02-06T21:26:57.248Z",
        "author_tryouts_string": "Sara Lund"
      }
    ],
    "nationality": "Latvian",
    "studyAtKTH": "",
    "studyDuration": "3 months",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Prefer not",
      "opposite": "Preferred",
      "middle": "Preferred",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Willing to train hard and commit to the team's goals.",
    "depositInfo": "",
    "teamExpectations": "Fully competitive",
    "availability": "",
    "source": "A friend told me about it",
    "previousExperience": "Played in a Club 4+ years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Women's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 96
  },
  {
    "id": "j1IHZv0WhLY1TXNNWMr91jpa",
    "name": "Ella Bj\u00f6rk",
    "email": "tbergstrom.volley@mail.com",
    "time": "1/21/2025 12:35:53",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Inconsistent but showed promise during warm-ups.",
        "id": "QQzOQ0gu4x",
        "date": "2025-02-04T19:31:01.949Z",
        "author_tryouts_string": "Mikaela Andersson"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Very powerful spikes, needs to work on consistency.",
        "id": "RIaLWUg5fx",
        "date": "2025-02-04T19:35:24.970Z",
        "author_tryouts_string": "Mikaela Andersson"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Lacked court awareness but adapted quickly by the end.",
        "id": "PzdxHawMc7",
        "date": "2025-02-04T19:58:39.940Z",
        "author_tryouts_string": "David Karlsson"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Played well under pressure and made very few errors.",
        "id": "wRtxcfdYJa",
        "date": "2025-02-04T20:27:07.273Z",
        "author_tryouts_string": "Sara Lund"
      },
      {
        "author": "Cm6Mf0trFCpC",
        "content": "Spikes were hard to receive, great offensive presence.",
        "id": "UmuDJb26M4",
        "date": "2025-02-04T22:10:37.034Z",
        "author_tryouts_string": "Fredrik Berg"
      },
      {
        "author": "FSg8syNtAKzY",
        "content": "Inconsistent but showed promise during warm-ups.",
        "id": "oaI7DejXh2",
        "date": "2025-02-05T15:01:39.228Z",
        "author_tryouts_string": "Emma Nystr\u00f6m"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "High potential, just needs more match experience.",
        "id": "4U5Iurh8ar",
        "date": "2025-02-04T21:46:57.789Z",
        "author_tryouts_string": "Erik Larsson"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Played well under pressure and made very few errors.",
        "id": "hFGbmvJ6gl",
        "date": "2025-02-06T08:55:41.620Z",
        "author_tryouts_string": "Johan Nilsson"
      }
    ],
    "nationality": "Dutch",
    "studyAtKTH": "",
    "studyDuration": "2+ years",
    "THSMember": "Yes",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Prefer not",
      "opposite": "Preferred",
      "middle": "Prefer not",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Looking for serious play with good vibes.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "KTH won division 3 last season",
    "previousExperience": "Played in a Club 2-4 years +",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 98
  },
  {
    "id": "sBI6Y49y6KE7K1fr1OP8Kox8",
    "name": "Oscar Dahl",
    "email": "jamie_a@kth.se",
    "time": "1/22/2025 15:40:45",
    "comments": [
      {
        "author": "l2ioN36H1a0g",
        "content": "Has solid fundamentals and a strong serve.",
        "id": "0hucZOW03D",
        "date": "2025-02-04T21:51:31.190Z",
        "author_tryouts_string": "Sara Lund"
      },
      {
        "author": "Cm6Mf0trFCpC",
        "content": "Sometimes hesitant when blocking, but good timing overall.",
        "id": "NrKEs2MSDX",
        "date": "2025-02-04T22:16:36.090Z",
        "author_tryouts_string": "Emma Nystr\u00f6m"
      }
    ],
    "nationality": "Finnish",
    "studyAtKTH": "",
    "studyDuration": "Not studying at KTH or other university",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Prefer not",
      "opposite": "Ok",
      "middle": "Ok",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Hoping to find a team that trains regularly.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "Instagram Page",
    "previousExperience": "Played in a Club 1-2 years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 8
  },
  {
    "id": "RWCqyqMhAO2v7FZPsiETGUWW",
    "name": "Nora Hellstr\u00f6m",
    "email": "j.lindqvist21@yahoo.com",
    "time": "1/22/2025 23:45:15",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Very powerful spikes, needs to work on consistency.",
        "id": "VEJtQfsw6i",
        "date": "2025-02-04T19:40:54.194Z",
        "author_tryouts_string": "Sara Lund"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Struggled a bit with positioning but has good potential.",
        "id": "NlrzuU7Ibz",
        "date": "2025-02-04T19:50:45.812Z",
        "author_tryouts_string": "David Karlsson"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Lacked court awareness but adapted quickly by the end.",
        "id": "WKWSKmDhn9",
        "date": "2025-02-04T19:55:21.762Z",
        "author_tryouts_string": "Fredrik Berg"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Needs to work on serve-receive but aggressive on the net.",
        "id": "F94BOvTjcE",
        "date": "2025-02-04T20:28:38.016Z",
        "author_tryouts_string": "David Karlsson"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Very powerful spikes, needs to work on consistency.",
        "id": "78WXcZrGcX",
        "date": "2025-02-04T21:52:25.958Z",
        "author_tryouts_string": "Johan Nilsson"
      },
      {
        "author": "Cm6Mf0trFCpC",
        "content": "Inconsistent but showed promise during warm-ups.",
        "id": "bHfkDxkmqG",
        "date": "2025-02-04T22:18:02.251Z",
        "author_tryouts_string": "Emma Nystr\u00f6m"
      },
      {
        "author": "FSg8syNtAKzY",
        "content": "Inconsistent but showed promise during warm-ups.",
        "id": "YK9T0uUF1N",
        "date": "2025-02-05T15:11:06.457Z",
        "author_tryouts_string": "Johan Nilsson"
      }
    ],
    "nationality": "French",
    "studyAtKTH": "",
    "studyDuration": "Not studying at KTH or other university",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Preferred",
      "opposite": "Prefer not",
      "middle": "Ok",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Hoping to find a team that trains regularly.",
    "depositInfo": "",
    "teamExpectations": "Fully competitive",
    "availability": "",
    "source": "A friend told me about it",
    "previousExperience": "Played in a Club 4+ years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 76
  },
  {
    "id": "RcHmD81NE6PPOntg6X5hzEAU",
    "name": "Liam Gustafsson",
    "email": "lucas.sandberg@gmail.com",
    "time": "1/23/2025 22:25:36",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Needs to work on serve-receive but aggressive on the net.",
        "id": "UK6oet5q2j",
        "date": "2025-02-04T20:46:19.969Z",
        "author_tryouts_string": "Erik Larsson"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Struggled a bit with positioning but has good potential.",
        "id": "MVprTp8EvI",
        "date": "2025-02-04T20:48:27.805Z",
        "author_tryouts_string": "Erik Larsson"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Inconsistent but showed promise during warm-ups.",
        "id": "d9SeIMQVHZ",
        "date": "2025-02-04T21:45:32.307Z",
        "author_tryouts_string": "Mikaela Andersson"
      },
      {
        "author": "FSg8syNtAKzY",
        "content": "Sometimes hesitant when blocking, but good timing overall.",
        "id": "wRgqVbkxHF",
        "date": "2025-02-05T14:58:35.147Z",
        "author_tryouts_string": "Mikaela Andersson"
      }
    ],
    "nationality": "German",
    "studyAtKTH": "",
    "studyDuration": "2+ years",
    "THSMember": "Yes",
    "preferredRoles": {
      "libero": "Preferred",
      "setter": "Ok",
      "opposite": "Ok",
      "middle": "Prefer not",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Hoping to find a team that trains regularly.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "Posters",
    "previousExperience": "Played in a Club 4+ years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 82
  },
  {
    "id": "F9GDa9OlrW1eP0UJl4FUbC0d",
    "name": "Liam Gustafsson",
    "email": "j.lindqvist21@yahoo.com",
    "time": "1/24/2025 14:02:57",
    "comments": [],
    "nationality": "German",
    "studyAtKTH": "",
    "studyDuration": "Not studying at KTH or other university",
    "THSMember": "I intend to become one soon",
    "preferredRoles": {
      "libero": "Ok",
      "setter": "Preferred",
      "opposite": "Ok",
      "middle": "Prefer not",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Played a lot before and now returning after a break.",
    "depositInfo": "",
    "teamExpectations": "Fully competitive",
    "availability": "",
    "source": "A friend told me about it",
    "previousExperience": "Played in a Club 2-4 years +",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Not paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 28
  },
  {
    "id": "WY7QVnmwlz1Qn0NBWnfed5Tx",
    "name": "Maja Eklund",
    "email": "j.lindqvist21@yahoo.com",
    "time": "1/24/2025 15:09:40",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Good communication on court, seems like a team player.",
        "id": "I0CfxEVBhO",
        "date": "2025-02-04T20:15:45.173Z",
        "author_tryouts_string": "David Karlsson"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Really solid middle blocker, reads the setter well.",
        "id": "ffOr4oS9Bi",
        "date": "2025-02-04T21:44:29.862Z",
        "author_tryouts_string": "Mikaela Andersson"
      },
      {
        "author": "Cm6Mf0trFCpC",
        "content": "Good communication on court, seems like a team player.",
        "id": "0YjHFRm9Yc",
        "date": "2025-02-04T22:11:23.447Z",
        "author_tryouts_string": "Emma Nystr\u00f6m"
      },
      {
        "author": "FSg8syNtAKzY",
        "content": "Has solid fundamentals and a strong serve.",
        "id": "LgxlqqsAwm",
        "date": "2025-02-05T14:56:45.976Z",
        "author_tryouts_string": "Mikaela Andersson"
      }
    ],
    "nationality": "Dutch",
    "studyAtKTH": "",
    "studyDuration": "1.5 years",
    "THSMember": "Yes",
    "preferredRoles": {
      "libero": "Ok",
      "setter": "Prefer not",
      "opposite": "Preferred",
      "middle": "Preferred",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Loves the sport and wants to play more competitively.",
    "depositInfo": "",
    "teamExpectations": "work on my skills in general",
    "availability": "",
    "source": "A friend told me about it",
    "previousExperience": "Played in a Club 1-2 years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 18
  },
  {
    "id": "7AOVuXSKDnMa3Rmd53m58vas",
    "name": "Liam Gustafsson",
    "email": "jamie_a@kth.se",
    "time": "1/24/2025 21:34:41",
    "comments": [
      {
        "author": "Cm6Mf0trFCpC",
        "content": "Very friendly, gave good energy to the team.",
        "id": "LL5EMUyf8e",
        "date": "2025-02-06T21:17:53.638Z",
        "author_tryouts_string": "Erik Larsson"
      }
    ],
    "nationality": "Dutch",
    "studyAtKTH": "",
    "studyDuration": "6 months",
    "THSMember": "I intend to become one soon",
    "preferredRoles": {
      "libero": "Preferred",
      "setter": "Ok",
      "opposite": "Prefer not",
      "middle": "Prefer not",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Willing to train hard and commit to the team's goals.",
    "depositInfo": "",
    "teamExpectations": "Social play",
    "availability": "",
    "source": "Instagram Page",
    "previousExperience": "Played in a Club 4+ years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Women's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 29
  },
  {
    "id": "IcsmStzWSX8ZLw2d7ThbqDWG",
    "name": "Nora Hellstr\u00f6m",
    "email": "riley.holmgren@gmail.com",
    "time": "1/24/2025 22:12:24",
    "comments": [
      {
        "author": "Cm6Mf0trFCpC",
        "content": "Great instincts and reads the game well.",
        "id": "S2et9HYdSo",
        "date": "2025-02-06T21:26:37.126Z",
        "author_tryouts_string": "David Karlsson"
      }
    ],
    "nationality": "Icelandic",
    "studyAtKTH": "",
    "studyDuration": "6 months",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Ok",
      "setter": "Preferred",
      "opposite": "Ok",
      "middle": "Prefer not",
      "wingSpiker": "Prefer not"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Previously coached youth teams, now wants to play.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "I searched by myself online ",
    "previousExperience": "Played in a Club 4+ years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Women's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 49
  },
  {
    "id": "yhWFpGcWPXqq3wq6dmLdCW0Q",
    "name": "Ella Bj\u00f6rk",
    "email": "riley.holmgren@gmail.com",
    "time": "1/26/2025 17:51:16",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Good communication on court, seems like a team player.",
        "id": "XicdfzXPn4",
        "date": "2025-02-04T19:51:39.308Z",
        "author_tryouts_string": "Sara Lund"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Great instincts and reads the game well.",
        "id": "YMGbVvXMWO",
        "date": "2025-02-04T20:46:03.620Z",
        "author_tryouts_string": "Mikaela Andersson"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Sometimes hesitant when blocking, but good timing overall.",
        "id": "WQalvvtQl7",
        "date": "2025-02-04T21:46:30.587Z",
        "author_tryouts_string": "Anna Sj\u00f6berg"
      },
      {
        "author": "FSg8syNtAKzY",
        "content": "Worked well in drills, could use more vocal presence.",
        "id": "PcI2brzBH5",
        "date": "2025-02-05T15:00:50.084Z",
        "author_tryouts_string": "Anna Sj\u00f6berg"
      }
    ],
    "nationality": "British",
    "studyAtKTH": "",
    "studyDuration": "2+ years",
    "THSMember": "Yes",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Ok",
      "opposite": "Preferred",
      "middle": "Preferred",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Excited to get back into volleyball after a year off.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "A friend told me about it",
    "previousExperience": "Casual Play only",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 53
  },
  {
    "id": "UA5mp2i87bxQkHx39QjEdAd5",
    "name": "Maja Eklund",
    "email": "maja.eklund@stud.kth.se",
    "time": "1/26/2025 18:25:50",
    "comments": [
      {
        "author": "Cm6Mf0trFCpC",
        "content": "Fantastic energy and motivation, lifts the team.",
        "id": "DAu5ZKu486",
        "date": "2025-02-06T21:25:03.190Z",
        "author_tryouts_string": "Erik Larsson"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Needs to work on serve-receive but aggressive on the net.",
        "id": "He84hQNoqD",
        "date": "2025-02-07T12:46:42.124Z",
        "author_tryouts_string": "Sara Lund"
      }
    ],
    "nationality": "Latvian",
    "studyAtKTH": "",
    "studyDuration": "Not studying at KTH or other university",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Ok",
      "setter": "Prefer not",
      "opposite": "Ok",
      "middle": "Prefer not",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Looking for serious play with good vibes.",
    "depositInfo": "",
    "teamExpectations": "Fully competitive",
    "availability": "",
    "source": "A friend told me about it",
    "previousExperience": "Played in a Club 2-4 years +",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Women's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 96
  },
  {
    "id": "t2fG060rGy91QkT8BG2b9G5W",
    "name": "Casey Ekstr\u00f6m",
    "email": "lucas.sandberg@gmail.com",
    "time": "1/27/2025 8:29:53",
    "comments": [],
    "nationality": "Latvian",
    "studyAtKTH": "",
    "studyDuration": "",
    "THSMember": "",
    "preferredRoles": {
      "libero": "",
      "setter": "",
      "opposite": "",
      "middle": "",
      "wingSpiker": ""
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Moving to Stockholm recently, looking for community.",
    "depositInfo": "",
    "teamExpectations": "",
    "availability": "",
    "source": "",
    "previousExperience": "",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "",
    "paid_deposit": "Not paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 81
  },
  {
    "id": "7VxVRyClHxFb1ZI8IjQK6WcP",
    "name": "Morgan Svensson",
    "email": "ella.bjork93@gmail.com",
    "time": "1/27/2025 17:11:41",
    "comments": [],
    "nationality": "French",
    "studyAtKTH": "",
    "studyDuration": "6 months",
    "THSMember": "I intend to become one soon",
    "preferredRoles": {
      "libero": "Preferred",
      "setter": "Preferred",
      "opposite": "Preferred",
      "middle": "Preferred",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Excited to get back into volleyball after a year off.",
    "depositInfo": "",
    "teamExpectations": "get good at volleyball and have fun.",
    "availability": "",
    "source": "A friend told me about it",
    "previousExperience": "Casual Play only",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Women's team",
    "paid_deposit": "Not paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 38
  },
  {
    "id": "T1B2Bh8OcVJNB9MAcuKAuotd",
    "name": "Maja Eklund",
    "email": "william.oberg91@yahoo.com",
    "time": "1/27/2025 19:27:15",
    "comments": [],
    "nationality": "Icelandic",
    "studyAtKTH": "",
    "studyDuration": "Not studying at KTH or other university",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Prefer not",
      "opposite": "Preferred",
      "middle": "Preferred",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Played a lot before and now returning after a break.",
    "depositInfo": "",
    "teamExpectations": "Social play",
    "availability": "",
    "source": "A friend told me about it",
    "previousExperience": "Played in a Club 2-4 years +",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Women's team",
    "paid_deposit": "Not paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 26
  },
  {
    "id": "NKc8pB07Q7495W1agshW4Nhm",
    "name": "Ella Bj\u00f6rk",
    "email": "jamie_a@kth.se",
    "time": "1/27/2025 20:36:47",
    "comments": [],
    "nationality": "Swedish",
    "studyAtKTH": "",
    "studyDuration": "1 year",
    "THSMember": "Yes",
    "preferredRoles": {
      "libero": "Ok",
      "setter": "Ok",
      "opposite": "Ok",
      "middle": "Ok",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Previously coached youth teams, now wants to play.",
    "depositInfo": "",
    "teamExpectations": "Fully competitive",
    "availability": "",
    "source": "Posters",
    "previousExperience": "High School",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Not paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 34
  },
  {
    "id": "MtDDGz8aBiDEw9vRwM8wOSgM",
    "name": "Lucas Sandberg",
    "email": "maja.eklund@stud.kth.se",
    "time": "1/27/2025 20:39:48",
    "comments": [],
    "nationality": "Finnish",
    "studyAtKTH": "",
    "studyDuration": "",
    "THSMember": "",
    "preferredRoles": {
      "libero": "",
      "setter": "",
      "opposite": "",
      "middle": "",
      "wingSpiker": ""
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Loves the sport and wants to play more competitively.",
    "depositInfo": "",
    "teamExpectations": "",
    "availability": "",
    "source": "",
    "previousExperience": "",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "",
    "paid_deposit": "Not paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 99
  },
  {
    "id": "fLe5k2ha4C5q54VUKv0AFHZT",
    "name": "Riley Holmgren",
    "email": "sofia.nyb@live.se",
    "time": "1/28/2025 13:29:51",
    "comments": [],
    "nationality": "Danish",
    "studyAtKTH": "",
    "studyDuration": "1.5 years",
    "THSMember": "I intend to become one soon",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Prefer not",
      "opposite": "Prefer not",
      "middle": "Preferred",
      "wingSpiker": "Prefer not"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Previously coached youth teams, now wants to play.",
    "depositInfo": "",
    "teamExpectations": "Fully competitive",
    "availability": "",
    "source": "I played many matches against KTH.",
    "previousExperience": "Played in a Club 4+ years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Not paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 41
  },
  {
    "id": "ANnTGn047DatYfjhMli39KsL",
    "name": "Maja Eklund",
    "email": "tbergstrom.volley@mail.com",
    "time": "1/28/2025 20:26:05",
    "comments": [],
    "nationality": "Latvian",
    "studyAtKTH": "",
    "studyDuration": "",
    "THSMember": "",
    "preferredRoles": {
      "libero": "",
      "setter": "",
      "opposite": "",
      "middle": "",
      "wingSpiker": ""
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Available most evenings and weekends.",
    "depositInfo": "",
    "teamExpectations": "",
    "availability": "",
    "source": "",
    "previousExperience": "",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "",
    "paid_deposit": "Not paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 30
  },
  {
    "id": "Ld9iM7Sx1ZsdXzkP344A9i6T",
    "name": "Jamie Andersson",
    "email": "oscar.dahl@outlook.com",
    "time": "1/28/2025 22:36:40",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Really solid middle blocker, reads the setter well.",
        "id": "xNIVBF4ooU",
        "date": "2025-02-04T19:35:51.775Z",
        "author_tryouts_string": "David Karlsson"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Worked well in drills, could use more vocal presence.",
        "id": "kGZcNXXXaG",
        "date": "2025-02-04T21:48:46.931Z",
        "author_tryouts_string": "Sara Lund"
      },
      {
        "author": "FSg8syNtAKzY",
        "content": "Sometimes hesitant when blocking, but good timing overall.",
        "id": "a8kj6k9gzs",
        "date": "2025-02-05T11:54:41.283Z",
        "author_tryouts_string": "Erik Larsson"
      }
    ],
    "nationality": "Dutch",
    "studyAtKTH": "",
    "studyDuration": "2+ years",
    "THSMember": "Yes",
    "preferredRoles": {
      "libero": "Preferred",
      "setter": "Preferred",
      "opposite": "Prefer not",
      "middle": "Ok",
      "wingSpiker": "Prefer not"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Excited to get back into volleyball after a year off.",
    "depositInfo": "",
    "teamExpectations": "Fully competitive",
    "availability": "",
    "source": "Instagram Page",
    "previousExperience": "High School",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 36
  },
  {
    "id": "djI9ufjPdoLMG8aSbW6l2tGy",
    "name": "Jordan Lindqvist",
    "email": "emil.norberg@stud.kth.se",
    "time": "1/29/2025 10:18:24",
    "comments": [
      {
        "author": "Cm6Mf0trFCpC",
        "content": "Fantastic energy and motivation, lifts the team.",
        "id": "iMTTWyoaYj",
        "date": "2025-02-06T21:21:09.981Z",
        "author_tryouts_string": "Anna Sj\u00f6berg"
      }
    ],
    "nationality": "Norwegian",
    "studyAtKTH": "",
    "studyDuration": "6 months",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Ok",
      "setter": "Prefer not",
      "opposite": "Ok",
      "middle": "Preferred",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Available most evenings and weekends.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "THS website",
    "previousExperience": "Played in a Club 1-2 years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Women's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 17
  },
  {
    "id": "B4u9xG72RlkmUvAB27gThNBS",
    "name": "Sofia Nyberg",
    "email": "tbergstrom.volley@mail.com",
    "time": "1/29/2025 11:02:21",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Very powerful spikes, needs to work on consistency.",
        "id": "aWn8L41RBn",
        "date": "2025-02-04T19:39:42.415Z",
        "author_tryouts_string": "Mikaela Andersson"
      },
      {
        "author": "FSg8syNtAKzY",
        "content": "Spikes were hard to receive, great offensive presence.",
        "id": "OPjJUOeKCg",
        "date": "2025-02-05T15:14:01.311Z",
        "author_tryouts_string": "Erik Larsson"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Lacked court awareness but adapted quickly by the end.",
        "id": "o1NbMTTXyD",
        "date": "2025-02-04T21:52:58.670Z",
        "author_tryouts_string": "Sara Lund"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Needs to work on serve-receive but aggressive on the net.",
        "id": "SC6mvJLayv",
        "date": "2025-02-06T09:01:02.634Z",
        "author_tryouts_string": "Fredrik Berg"
      }
    ],
    "nationality": "British",
    "studyAtKTH": "",
    "studyDuration": "1 year",
    "THSMember": "I intend to become one soon",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Ok",
      "opposite": "Preferred",
      "middle": "Ok",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Open to any position, just wants to be on court.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "THS Sports",
    "previousExperience": "High School",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 32
  },
  {
    "id": "yTWIlOYlWYBjXH8DILHcwmwp",
    "name": "Maja Eklund",
    "email": "sofia.nyb@live.se",
    "time": "1/30/2025 13:55:09",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Inconsistent but showed promise during warm-ups.",
        "id": "CLjVsjl78i",
        "date": "2025-02-04T19:55:09.571Z",
        "author_tryouts_string": "Fredrik Berg"
      },
      {
        "author": "FSg8syNtAKzY",
        "content": "Very friendly, gave good energy to the team.",
        "id": "zVq2Kscl3L",
        "date": "2025-02-05T15:15:39.560Z",
        "author_tryouts_string": "Anna Sj\u00f6berg"
      }
    ],
    "nationality": "Swedish",
    "studyAtKTH": "",
    "studyDuration": "1.5 years",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Ok",
      "setter": "Prefer not",
      "opposite": "Ok",
      "middle": "Ok",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Wants to compete and also have fun.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "A friend told me about it",
    "previousExperience": "Casual Play only",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 96
  },
  {
    "id": "o3HICUmnCwsSj9lrltCeq8D9",
    "name": "Riley Holmgren",
    "email": "tbergstrom.volley@mail.com",
    "time": "1/30/2025 14:00:07",
    "comments": [],
    "nationality": "Latvian",
    "studyAtKTH": "",
    "studyDuration": "",
    "THSMember": "",
    "preferredRoles": {
      "libero": "",
      "setter": "",
      "opposite": "",
      "middle": "",
      "wingSpiker": ""
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Willing to train hard and commit to the team's goals.",
    "depositInfo": "",
    "teamExpectations": "",
    "availability": "",
    "source": "",
    "previousExperience": "",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "",
    "paid_deposit": "Not paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 20
  },
  {
    "id": "q1sGCkdMjyc1nUsh63tlGWsZ",
    "name": "Jamie Andersson",
    "email": "alex.johansson95@gmail.com",
    "time": "1/31/2025 0:30:34",
    "comments": [
      {
        "author": "Cm6Mf0trFCpC",
        "content": "Struggled a bit with positioning but has good potential.",
        "id": "wVmAchOYuW",
        "date": "2025-02-06T21:28:04.281Z",
        "author_tryouts_string": "Anna Sj\u00f6berg"
      }
    ],
    "nationality": "French",
    "studyAtKTH": "",
    "studyDuration": "2 years",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Prefer not",
      "opposite": "Ok",
      "middle": "Prefer not",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Hoping to find a team that trains regularly.",
    "depositInfo": "",
    "teamExpectations": "Fully competitive",
    "availability": "",
    "source": "Instagram Page",
    "previousExperience": "Played in a Club 4+ years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Women's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 49
  },
  {
    "id": "ag93cXhPzSKekUsNtEZnCqB4",
    "name": "William \u00d6berg",
    "email": "ella.bjork93@gmail.com",
    "time": "1/31/2025 8:24:28",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Very friendly, gave good energy to the team.",
        "id": "QjvAg6ka0v",
        "date": "2025-02-04T19:23:55.150Z",
        "author_tryouts_string": "David Karlsson"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "High potential, just needs more match experience.",
        "id": "M1Sk3ruqtv",
        "date": "2025-02-04T19:24:02.066Z",
        "author_tryouts_string": "Sara Lund"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Played well under pressure and made very few errors.",
        "id": "uXNb5glYpq",
        "date": "2025-02-04T19:40:30.980Z",
        "author_tryouts_string": "Anna Sj\u00f6berg"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Good communication on court, seems like a team player.",
        "id": "7MDwWoZ5pn",
        "date": "2025-02-04T21:56:03.636Z",
        "author_tryouts_string": "Erik Larsson"
      },
      {
        "author": "FSg8syNtAKzY",
        "content": "Very friendly, gave good energy to the team.",
        "id": "ZoZOzagsl4",
        "date": "2025-02-05T11:52:56.391Z",
        "author_tryouts_string": "David Karlsson"
      }
    ],
    "nationality": "Estonian",
    "studyAtKTH": "",
    "studyDuration": "6 months",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Prefer not",
      "setter": "Ok",
      "opposite": "Preferred",
      "middle": "Prefer not",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Open to any position, just wants to be on court.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "Instagram Page",
    "previousExperience": "Played in a Club 1-2 years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 18
  },
  {
    "id": "1XtB28RA2wg8Du1vlxB1P69P",
    "name": "Alex Johansson",
    "email": "tbergstrom.volley@mail.com",
    "time": "1/31/2025 15:27:25",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Spikes were hard to receive, great offensive presence.",
        "id": "a71DmEmkJa",
        "date": "2025-02-04T19:24:28.380Z",
        "author_tryouts_string": "Anna Sj\u00f6berg"
      },
      {
        "author": "FSg8syNtAKzY",
        "content": "Spikes were hard to receive, great offensive presence.",
        "id": "cwaVAmvq1q",
        "date": "2025-02-05T15:09:41.948Z",
        "author_tryouts_string": "David Karlsson"
      }
    ],
    "nationality": "Norwegian",
    "studyAtKTH": "",
    "studyDuration": "2+ years",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Ok",
      "setter": "Ok",
      "opposite": "Preferred",
      "middle": "Ok",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Looking for serious play with good vibes.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "Instagram Page",
    "previousExperience": "Played in a Club 4+ years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 89
  },
  {
    "id": "hm8ThTeeW5PxoFn8gto2K14p",
    "name": "Oscar Dahl",
    "email": "liam.gustafsson@kth.se",
    "time": "1/31/2025 16:39:18",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Struggled a bit with positioning but has good potential.",
        "id": "mTZX0O3If8",
        "date": "2025-02-04T19:12:13.961Z",
        "author_tryouts_string": "Mikaela Andersson"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Lacked court awareness but adapted quickly by the end.",
        "id": "yGLWIorwXj",
        "date": "2025-02-04T19:22:18.681Z",
        "author_tryouts_string": "Emma Nystr\u00f6m"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Very friendly, gave good energy to the team.",
        "id": "WObAt2RJJT",
        "date": "2025-02-04T19:25:24.255Z",
        "author_tryouts_string": "Sara Lund"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Has solid fundamentals and a strong serve.",
        "id": "IoxlAq0ctw",
        "date": "2025-02-04T19:40:07.143Z",
        "author_tryouts_string": "David Karlsson"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Fantastic energy and motivation, lifts the team.",
        "id": "cx3oyf3mVn",
        "date": "2025-02-04T19:40:35.918Z",
        "author_tryouts_string": "Erik Larsson"
      },
      {
        "author": "FSg8syNtAKzY",
        "content": "Very friendly, gave good energy to the team.",
        "id": "Oii9UFNm0v",
        "date": "2025-02-05T15:05:43.659Z",
        "author_tryouts_string": "Emma Nystr\u00f6m"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Great instincts and reads the game well.",
        "id": "VnXeZNx3sp",
        "date": "2025-02-04T21:48:22.375Z",
        "author_tryouts_string": "Mikaela Andersson"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Has solid fundamentals and a strong serve.",
        "id": "FPBa3CkddN",
        "date": "2025-02-06T08:56:19.623Z",
        "author_tryouts_string": "Emma Nystr\u00f6m"
      }
    ],
    "nationality": "German",
    "studyAtKTH": "",
    "studyDuration": "6 months",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Preferred",
      "setter": "Ok",
      "opposite": "Ok",
      "middle": "Prefer not",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Excited to get back into volleyball after a year off.",
    "depositInfo": "",
    "teamExpectations": "Slight specialization (i.e work seriously on specialized role skills)",
    "availability": "",
    "source": "Facebook (KTH Volleyball)",
    "previousExperience": "Played in a Club 4+ years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 50
  },
  {
    "id": "q0cZqYgUbV4J6Ebd6BrWFt1f",
    "name": "Emil Norberg",
    "email": "riley.holmgren@gmail.com",
    "time": "1/31/2025 19:29:29",
    "comments": [
      {
        "author": "TfJwmrXmoUkT",
        "content": "Struggled a bit with positioning but has good potential.",
        "id": "FexKKYw1TF",
        "date": "2025-02-04T19:37:44.780Z",
        "author_tryouts_string": "David Karlsson"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Sometimes hesitant when blocking, but good timing overall.",
        "id": "eFAL6oGYcX",
        "date": "2025-02-04T20:26:02.878Z",
        "author_tryouts_string": "Fredrik Berg"
      },
      {
        "author": "TfJwmrXmoUkT",
        "content": "Has solid fundamentals and a strong serve.",
        "id": "7cIAO73f0T",
        "date": "2025-02-04T20:28:49.524Z",
        "author_tryouts_string": "Mikaela Andersson"
      },
      {
        "author": "Cm6Mf0trFCpC",
        "content": "Really solid middle blocker, reads the setter well.",
        "id": "Anf72PNZ2P",
        "date": "2025-02-04T22:14:37.584Z",
        "author_tryouts_string": "Emma Nystr\u00f6m"
      },
      {
        "author": "EF1UcqRtoxX0",
        "content": "Lacked court awareness but adapted quickly by the end.",
        "id": "T3ap8FoLa9",
        "date": "2025-02-04T23:40:57.281Z",
        "author_tryouts_string": "Erik Larsson"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Played well under pressure and made very few errors.",
        "id": "nvozYBLchm",
        "date": "2025-02-04T21:50:09.764Z",
        "author_tryouts_string": "Sara Lund"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Inconsistent but showed promise during warm-ups.",
        "id": "Dh7xrHdSiW",
        "date": "2025-02-06T08:57:42.524Z",
        "author_tryouts_string": "David Karlsson"
      }
    ],
    "nationality": "Latvian",
    "studyAtKTH": "",
    "studyDuration": "Not studying at KTH or other university",
    "THSMember": "No",
    "preferredRoles": {
      "libero": "Ok",
      "setter": "Prefer not",
      "opposite": "Ok",
      "middle": "Ok",
      "wingSpiker": "Ok"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Excited to get back into volleyball after a year off.",
    "depositInfo": "",
    "teamExpectations": "Social play",
    "availability": "",
    "source": "A friend told me about it",
    "previousExperience": "Casual Play only",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 56
  },
  {
    "id": "zS5Omxye02cHusO6wID5lmN3",
    "name": "Emil Norberg",
    "email": "morgan.svensson@hotmail.com",
    "time": "2/1/2025 21:05:06",
    "comments": [
      {
        "author": "FSg8syNtAKzY",
        "content": "Has solid fundamentals and a strong serve.",
        "id": "NW1KltoCqo",
        "date": "2025-02-05T15:08:48.628Z",
        "author_tryouts_string": "Erik Larsson"
      },
      {
        "author": "l2ioN36H1a0g",
        "content": "Needs to work on serve-receive but aggressive on the net.",
        "id": "XdlSG8uuCY",
        "date": "2025-02-06T08:59:04.767Z",
        "author_tryouts_string": "Anna Sj\u00f6berg"
      }
    ],
    "nationality": "Latvian",
    "studyAtKTH": "",
    "studyDuration": "2+ years",
    "THSMember": "I intend to become one soon",
    "preferredRoles": {
      "libero": "Ok",
      "setter": "Prefer not",
      "opposite": "Preferred",
      "middle": "Ok",
      "wingSpiker": "Preferred"
    },
    "regularForKorpen": "",
    "participationFrequency": "",
    "additionalInfo": "Interested in both korpen and league games.",
    "depositInfo": "",
    "teamExpectations": "Social play",
    "availability": "",
    "source": "Posters",
    "previousExperience": "Played in a Club 1-2 years",
    "boardPositionInterest": "",
    "availableTimes": "",
    "teamAppliedFor": "Men's team",
    "paid_deposit": "Has paid",
    "deposit_returned": "Not returned",
    "picture": "https://studs-stage.s3.amazonaws.com/uploads/1743433625513/20241108_174954.jpg",
    "tryouts_shirt_number": 86
  }
];

export interface Applicant {
  [key: string]: any;
}